spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://172.26.148.213:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://47.92.116.67:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: admin
    password: 123456
#    host: 127.0.0.1
    host: 47.92.116.67
    publisher-confirms: true
    publisher-returns: true
  redis:
#    host: 127.0.0.1
    host: 47.92.116.67
    database: 0
    port: 6379
    password: 123456
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://47.92.116.67/